[project]
name = "langgraph-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.25",
    "langchain-nvidia-ai-endpoints>=0.3.10",
    "langgraph>=0.4.8",
]
